#!/bin/bash

filename=$1
cfg_file=$2
eig_file=$3
prop_file=$4
T=$5

ssize=32
tsize=64

num_vecs=96
smear_fact=0.08
smear_num=10

cat <<EOF > ${filename}
<?xml version="1.0"?>
<chroma>
 <Param>
  <InlineMeasurements>
    <elem>
      <Name>PROP_AND_MATELEM_DISTILLATION_SUPERB</Name>
      <Frequency>1</Frequency>
      <Param>
        <Contractions>
          <mass_label>U-0.2350</mass_label>
          <num_vecs>$num_vecs</num_vecs>
          <t_sources>$T</t_sources>
          <Nt_forward>21</Nt_forward>
          <Nt_backward>21</Nt_backward>
          <decay_dir>3</decay_dir>
          <num_tries>-1</num_tries>
          <max_rhs>1</max_rhs>
          <phase>0.00 0.00 0.00</phase>
        </Contractions>
        <Propagator>
          <version>10</version>
          <quarkSpinType>FULL</quarkSpinType>
          <obsvP>false</obsvP>
          <numRetries>1</numRetries>

          <FermionAction>
            <FermAct>CLOVER</FermAct>
            <Mass>-0.2350</Mass>
            <clovCoeff>1.20536588031793</clovCoeff>
            <AnisoParam>
              <anisoP>false</anisoP>
              <t_dir>3</t_dir>
              <xi_0>1</xi_0>
              <nu>1</nu>
            </AnisoParam>
            <FermState>
              <Name>STOUT_FERM_STATE</Name>
              <rho>0.125</rho>
              <n_smear>1</n_smear>
              <orthog_dir>-1</orthog_dir>
              <FermionBC>
                <FermBC>SIMPLE_FERMBC</FermBC>
                <boundary>1 1 1 -1</boundary>
              </FermionBC>
            </FermState>
          </FermionAction>
          <InvertParam>
            <invType>QPHIX_CLOVER_ITER_REFINE_BICGSTAB_INVERTER</invType>
            <SolverType>BICGSTAB</SolverType>
            <MaxIter>200000</MaxIter>
            <RsdTarget>1.0e-12</RsdTarget>
            <Delta>0.01</Delta>
            <CloverParams>
              <Mass>-0.2350</Mass>
              <clovCoeff>1.20536588031793</clovCoeff>
              <AnisoParam>
                <anisoP>false</anisoP>
                <t_dir>3</t_dir>
                <xi_0>1</xi_0>
                <nu>1</nu>
              </AnisoParam>
            </CloverParams>
            <AntiPeriodicT>true</AntiPeriodicT>
            <Verbose>false</Verbose>
            <RsdToleranceFactor>10</RsdToleranceFactor>
            <Tune>false</Tune>
          </InvertParam>
        </Propagator>
      </Param>
      <NamedObject>
        <gauge_id>default_gauge_field</gauge_id>
        <colorvec_files><elem>${eig_file}</elem></colorvec_files>
        <prop_op_file>${prop_file}</prop_op_file>
      </NamedObject>
    </elem>
  </InlineMeasurements>
  <nrow>$ssize $ssize $ssize $tsize</nrow>
  </Param>
  <RNG>
    <Seed>
      <elem>2551</elem>
      <elem>3189</elem>
      <elem>2855</elem>
      <elem>707</elem>
    </Seed>
  </RNG>
  <Cfg>
    <cfg_type>SCIDAC</cfg_type>
    <cfg_file>${cfg_file}</cfg_file>
    <parallel_io>true</parallel_io>
  </Cfg>
</chroma>
EOF
